### ISSUE TITLE
What software/cloud tools do you use to help run your community?

### ISSUE THREAD

**Issue by jduckles** [carpentries/community-cookbook#1]
I've begun to list tools useful for running a campus/regional community. Please add other tools you use to this issue, or submit a PR to this file and we'll add them in.

Things like:
* Mailing list software
* video conferencing tools
* collaboration platforms and tools
* shared calendars

Submissions will be added to:

https://github.com/carpentries/community-cookbook/blob/master/tools/00-index.md

**Comment by sstevens2** [comment]
We use:
- the university's listserv software
- github pages for website (used to use google sites)
- google calendar built into the webpage
- shared admin google drive

**Comment by lexnederbragt** [comment]
We use

* the university's listserv software
* university's questionnaire form system for registrations/surveys
* Science Library pages for website and workshop websites
* google calendar for events (only internally amongst instructors)
* github organisation for workshop website pages
* github pages for our own website, a single page with all our past workshops
* github repo for meeting minutes and other organisational stuff

**Comment by jduckles** [comment]
I've tried to capture most of your points in the above commit @lexnederbragt and @sstevens2. Still need to flesh out these sections, PRs welcome if you have the time or inkling. Thanks for sharing your insight!
