### ISSUE TITLE
Gathering Local Community Websites

### ISSUE THREAD

**Issue by jduckles** [carpentries/community-cookbook#26]
Based on the Champions call blog post list of Carpentry Community websites, this is a place to collect other community websites that should be included in the next update of the community-cookbook. 

The current list is: 

- [Study Group - The University of Otago, Dunedin, NZ](https://otagocarpentries.github.io)
- [UF Carpentries Club](https://www.uf-carpentries.org)
- [Software Carpentry and Data Carpentry at The University of Oklahoma](https://libraries.ou.edu/content/software-and-data-carpentry)
- [New England Software Carpentry Library Consortium](https://nesclic.github.io)
- [Carpentry @ UiO](https://www.ub.uio.no/english/courses-events/courses/other/Carpentry/software-carpentry/)
- [The Software Sustainability Institute](https://software.ac.uk/programmes-events/carpentries/software-carpentry)
- [eScience at University of Washington](https://escience.washington.edu)
- [The University of Wisconsin - Madison](https://hub.datascience.wisc.edu/training)
- [Data Science at UCSF](https://www.library.ucsf.edu/ask-an-expert/data-science/)
- [Illinois - Hands on with CSE](https://cse.illinois.edu/cse-training/)
- [UC Berkeley Carpentries Club](https://bids.berkeley.edu/research/berkeley-carpentries-club)
- [UChicago Carpentries Club](https://uc-carpentries.github.io)
- [Smithsonian Carpentries Group](https://datascience.si.edu/carpentries)

Please add yours if I missed it, or you know about another one by commenting on this issue with the link.

**Comment by lexnederbragt** [comment]
Could you use https://uio-carpentry.github.io for Oslo, and maybe call it 'Carpentry @ Univ. of Oslo'?

**Comment by jduckles** [comment]
Added in via 48fb580d32f9e0032dc7a28d5c5834301a0dc17f
